services:
  encodapy-mqtt:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: encodapy-mqtt-container

    extra_hosts:
      - "host.docker.internal:host-gateway"

    env_file:
      - .env

    volumes:
      - ./config.json:/app/config.json
      - ./custom_mqtt_template.json:/app/custom_mqtt_template.json
      - ./main.py:/app/main.py
      - ./mqtt_controller.py:/app/mqtt_controller.py

    command: python main.py

    restart: unless-stopped
