services:
  encodapy-mqtt:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: encodapy-mqtt-container

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      LOG_LEVEL: DEBUG
      MQTT_TEMPLATE_EXAMPLE05: custom_mqtt_template.json
      MQTT_PUBLISH_DELAY: 2
      CONFIG_PATH: ./config.json
      LOG_PATH: ./logs/example05_simple_service_mqtt.log
      MQTT_HOST: host.docker.internal
      MQTT_PORT: "1883"

    volumes:
      - ./config.json:/app/config.json
      - ./custom_mqtt_template.json:/app/custom_mqtt_template.json
      - ./main.py:/app/main.py
      - ./mqtt_controller.py:/app/mqtt_controller.py

    command: python main.py

    restart: unless-stopped
